---
- hosts: web
  remote_user: root
  tasks:
   - name: Installing Latest version of Apache
     yum: pkg=httpd state=latest
   - name: Copying the demo file
     template: src=./index.html dest=/var/www/html
       owner=apache group=apache mode=0644
   - name: (Enable it on System Boot)
     service: name=httpd enabled=yes
     notify:
      - start apache
   - name: open firewall
     command: 'firewall-cmd --permanent --add-port=80/tcp'
     notify:
      - reload firewall
  handlers:
    - name: start apache
      service: name=httpd state=started
    - name: reload firewall
      command: 'firewall-cmd --reload'

- hosts: localhost
  remote_user: root
  tasks:
   - command: curl http://192.168.99.103
     register: shell_result

   - debug:
        var: shell_result.stdout_lines
   #- name: web verification
   #  uri:
   #    url: http://192.168.99.103
   #  register: uri_result
   #- debug:
   #    var: uri_result.stdout_lines
