---
- name: Ansible  Example
  hosts: localhost
  vars:
    data: "ab,cd"
    cond1: "'abcd' in out.stdout"
    cond2: "'cde' in out.stdout"
    output_variable:
      - abc
      - cde
    condition_variable:
      - "'abc' in out.stdout"
      - "'cde' in out.stdout"
  tasks:
    - shell: echo {{output_variable}}
      register: out
      until: 
        - "'abcd' in out.stdout"
        - "'cde' in out.stdout"
      retries: 10
      delay: 2
    
   

  