---
- name: Ansible Find Example
  hosts: all
  tasks:
    - name: Validate if the file is present
      shell: ls -lrt /tmp/test
      register: lsresult
      until: "lsresult is not failed"
      retries: 10
      delay: 10

  