---
- name: Ansible Find Example
  hosts: all
  vars_files:
    - default_step.yml
  vars:
    data: "ab,cd"

  tasks:
    - name: Split string into list
      set_fact:
        cond_list: "{{ data.split(',') | map('regex_replace', '^(.*)$', \"'\\1 is running' in out.stdout\") | list }}"
    - debug:
        var: cond_list
    - name: Validate if the file is present
      shell: cat /tmp/test
      register: out
      until: 
        - "'abc is running' in out.stdout"
      retries: 10
      delay: 2
    
    

  