---
- name: Ansible Find Example
  hosts: all
  vars:
    data: "abcd,pqrsr"
    my_regex: 'abcd\npqrsr'
  tasks:
    - name: Split string into list
      set_fact:
        condlist: "{{ data.split(',') | map('regex_replace', '^(.*)$', \"component \\1 is running\"  ) | list }}"
    - debug:
        var: condlist
    - name: Split string into list
      set_fact:
        cond_list: "{{ data | regex_replace(',', '\\n') }}"
    - debug:
        var: " cond_list"
    - name: Validate if the file is present
      shell: cat /tmp/test
      register: result
      until: result.stdout is search(cond_list)
      #until: [('abcde' in out.stdout) , ('pqrsr' in out.stdout)]
      retries: 2
      delay: 2
    
    

  