---
- name: Ansible  Example
  hosts: localhost
  vars:
    data: "ab,cd"
    output_variable:
      - 'abc'
      - 'cde'
    condition_variable:
      - "'abcd' in out.stdout"
      - "'cdef' in out.stdout"
  tasks:
    - shell: echo {{output_variable}}
      register: out
      until: condition_variable
      retries: 10
      delay: 2
    
   

  