---
- name: Ansible  Example
  hosts: localhost
  vars:
    data: "ab,cd"
    output_variable:
      - abc
      - cde
    condition_variable:
      - "'abc' in out.stdout_lines"
      - "'cde' in out.stdout_lines"
  tasks:
    - shell: echo {{output_variable}}
      register: out
      until: 
        - "'abc' in out.stdout_lines"
        - "'cde' in out.stdout_lines"
      retries: 10
      delay: 2
    
   

  