---
- name: Ansible Find Example
  hosts: all
  vars_files:
    - default_step.yml
  vars:
    data: "ab,cd"

  tasks:
    - name: Split string into list
      set_fact:
        my_list: "{{ data.split(',') | map('regex_replace', '^(.*)$', '\'\\1 is running\' in out.stdout') | list }}"
    - debug:
        var: my_list
    - name: Validate if the file is present
      shell: cat /tmp/test
      register: out
      until: "'ab is running'  in out.stdout"
      retries: 10
      delay: 2
    
    - name: Print the List
      debug:
        msg: "{{ my_list }}"

    - name: Concatenate a list to string
      set_fact:
        my_string: "{{ my_list | join(',') }}"

    - name: Print the String
      debug:
        msg: "{{ my_string }}"

  