---
- name: Ansible Find Example
  hosts: all
  tasks:
    - name: Validate if the file is present
      shell: cat /tmp/test
      register: out
      until: "'running'  in out.stdout"
      retries: 10
      delay: 2

  