---
- name: Ansible Find Example
  hosts: all
  vars:
    data: "abcd,pqrs"
  tasks:
    - name: show file content
      shell: cat /tmp/test
      register: showfile
    - debug:
        var: showfile.stdout_lines
    - name: Split string into list
      set_fact:
        cond_list: "{{ data.split(',') | map('regex_replace', '^(.*)$', \('\\1 is running' in out.stdout\) | list }}"
    - debug:
        var: cond_list
    - name: Validate if the file is present
      shell: cat /tmp/test
      register: out
      until: [('abcd' in out.stdout) , ('pqrs' in out.stdout)]
      retries: 10
      delay: 2
    
    

  