---
- name: Ansible Find Example
  hosts: all
  vars:
    data: "ab,cd"
    output_variable:
      - "'ab is running' in out.stdout"
      - "'cd is running' in out.stdout"
    cond_list_variable:
      - "'abc is running' in out.stdout"
      - "'cd is running' in out.stdout"
  tasks:
    - name: Split string into list
      set_fact:
        cond_list: "{{ data.split(',') | map('regex_replace', '^(.*)$', \"'\\1 is running' in out.stdout\") | list }}"
    - debug:
        var: cond_list
    - debug:
        var: cond_list_variable
    - name: Validate if the file is present
      shell: echo {{output_variable}}
      register: out
      until: cond_list_variable
        #- "'abc is running' in out.stdout"
        #- "'cd is running' in out.stdout"
      retries: 10
      delay: 2
    
   

  