---
- name: Ansible Find Example
  hosts: all
  tasks:
  - name: Register loop output as a variable
    shell: "echo {{ item }}"
    loop:
      - "one"
      - "two"
  register: echo
    - name: Validate if the file is present
      shell: cat /tmp/test
      register: out
      until: "'ab is running'  in out.stdout"
      retries: 10
      delay: 2

  