---
- name: Ansible Find Example
  hosts: all
  vars:
    data: "abcd,pqrs"
  tasks:
    - debug:
         var: my_regex
    - name: show file content
      shell: cat /tmp/test
      register: showfile
    - debug:
        var: "showfile.stdout_lines"
    - name: Split string into list
      set_fact:
        my_regex: "{{ data | replace(',', '\|') }}"
    - debug:
        var: "my_regex"
    - name: Validate if the file is present
      shell: cat /tmp/test
      register: result
      until: result.stdout is search(my_regex)
      #until: [('abcde' in out.stdout) , ('pqrsr' in out.stdout)]
      retries: 2
      delay: 2
    
    

  