---
- name: Ansible Example
  hosts: all
  gather_facts: false
  vars:
    command: "cat /tmp/test"
    keys_required:
      - 'abcd'
      - 'pqrs'
    keys_query: "['abcd', 'pqrs']"
  tasks:
    - name: Run command and register output
      shell: "{{ command }}"
      register: command_output
      until: command_output.stdout | from_json | json_query(keys_query) == keys_required
      retries: 10
      delay: 2
     