---
- name: Ansible Find Example
  hosts: all
  vars:
    data: "ab,cd"
    output_variable:
      - abc
      - cde
    condition_variable:
      - "'abc' in out.stdout"
      - "'cde' in out.stdout"
  tasks:
    - name: Validate if the file is present
      shell: echo {{output_variable}}
      register: out
      until: cond_list_variable
      retries: 10
      delay: 2
    
   

  