#!/bin/bash  
    echo "params1=$params"
    echo "Inventory2=${Inventory}"
    echo "myFilesfull3=${myFilesfull}"
    echo "myFilenames4=${myFilenames}"
    echo "myFilenames5=$myFilenames"
    echo "Tool_install6=$Tool_install"
    echo "MY_VAR1=$params.MY_VAR"
    echo "MY_VAR2=${env.MY_VAR}"
    echo "MY_VAR2=${MY_VAR}"