#!/bin/bash  
    echo "MY_VAR_P=$MY_VAR_P"
    echo "MY_VAR_E=${MY_VAR_E}"
    echo "myFilesfull3=${myFilesfull}"
    echo "myFilenames4=${myFilenames}"
    echo "myFilenames5=$myFilenames"
    echo "Tool_install6=$Tool_install"
    echo "MY_VAR_PAR=${MY_VAR}"
    echo "MY_VAR_ENV=${MY_VAR}"
    echo "MY_VAR=${MY_VAR}"