---
  - name: Shell Examples
    hosts: all
    tasks:
      - include_vars: vars/values.yml

      - name: Transfer the script
        register: copyfile
        copy: src=test.sh dest=/root mode=0777

      - name: Execute the script
        register: listfile
        command: sh /root/test.sh ${ myenv }
      
      - debug:
          var: listfile.stdout_lines
