b---
  - name: Shell Examples
    hosts: all
    tasks:
      - include_vars: vars/values.yml

      - name: Execute local script in remote
        register: listfile
        script:
          executable: /bin/bash 
          cmd: localtest9.sh ${myenv}
      - debug:
          var: listfile.stdout_lines

      - name: Execute command in remote
        register: listfile
        shell: cp test /tmp && cat /tmp/test
      - debug:
         var: listfile.stdout_lines

      - name: Execute the script
        register: listfile
        command:  cat /tmp/test
      - debug:
         var: listfile.stdout_lines
